# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.IntegerField(default=None),
        ),
    ]
