# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20160406_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telegram_id',
            field=models.IntegerField(default=-1),
        ),
    ]
