# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('processed_text', models.TextField()),
                ('deleted', models.BooleanField()),
                ('processed', models.BooleanField(default=False)),
                ('processing_start_time', models.IntegerField(default=0)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
