# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20160415_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, upload_to=models.CharField(default='', max_length=100)),
        ),
    ]
